### PR TITLE
change docker hub link

### PR DESCRIPTION
**Pull request by xc0derx**
I have read the CLA Document and I hereby sign the CLA

### CODE REVIEW

**Comment by xc0derx** [comment]
recheck

**Comment by xc0derx** [comment]
recheck

**Comment by SaltTan** [comment]
@xc0derx could you please post the CLA comment one more time?

**Comment by xc0derx** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by xc0derx** [comment]
recheck

**Comment by SaltTan** [comment]
@xc0derx thank you!

**Pull request merged**
